### ISSUE TITLE
P.27 `getConverter`での型エラー

### ISSUE THREAD

**Issue by phasetr** [SonicGarden/testable-firebase-sample-chat#14]
本をはじめから写経していて`src/lib/firebase.ts`の`getConverter`で次のエラーが出ました。

>TS2322: Type '(snapshot: QueryDocumentSnapshot<T>, options: SnapshotOptions) => WithId<T>' is not assignable to type '(snapshot: QueryDocumentSnapshot<DocumentData>, options?: SnapshotOptions | undefined) => WithId<T>'.   Types of parameters 'snapshot' and 'snapshot' are incompatible.     Type 'QueryDocumentSnapshot<DocumentData>' is not assignable to type 'QueryDocumentSnapshot<T>'.       Type 'DocumentData' is not assignable to type 'T'.         'T' could be instantiated with an arbitrary type which could be unrelated to 'DocumentData'.  [index.d.ts(684, 5)](https://github.com/SonicGarden/testable-firebase-sample-chat/issues/new#navigation_logical//Users/sekine/dev/testable-firebase-sample-chat/node_modules/@firebase/firestore/dist/index.d.ts:684:5): The expected type comes from property 'fromFirestore' which is declared here on type 'FirestoreDataConverter<WithId<T>>'

まだFirebase（とTypeScript）に慣れていないため自力でエラーの修正ができませんでした。どうするとエラーが消せるでしょうか？

また、リポジトリから完成版をクローンして確認したところ、エディタ上ではエラーが出ているもののビルドは通りました。

**Comment by konti-kun** [comment]
ご指摘ありがとうございます。確かに型エラー出てますね。

getConverterのところで、以下の通り`extends DocumentData`を入れればエラーは消えます。
```
const getConverter = <T extends DocumentData>(): FirestoreDataConverter<WithId<T>> => ({
```

TがDocumentDataを継承しているって意味なんですが、DocumetDataがobjectであることくらいしか定義されてないのでエラーは出ていましたが実質問題ないやつでした。

レポジトリの方も直しておきます！

**Comment by phasetr** [comment]
エラー解消確認しました。ありがとうございます。

**Comment by phasetr** [comment]
上記修正の影響でP.30の`setCollection`でも`extends`が必要になるようです。多分他にもはねると思うので、読み進めながらここに記録します。

**Comment by hiroro-work** [comment]
@phasetr 

ご連絡ありがとうございます！助かります！

こちらのエラーですが、TSバージョンがエディタと本アプリで異なる場合に発生する可能性がありそうです。
私の開発環境で確認したところVSCodeのTSバージョンは`4.8.2`になっておりアプリのTSバージョン（`4.7.4`）より新しくなっていましたので、アプリ開発時よりTSチェックが厳しくなってエラーが発生するようになったようです。

なのでエディタが使用するTSバージョンをアプリのTSバージョンに合わせていただくことでもTSエラーの発生は防ぐことができそうです。
もちろん上でご説明させていただいたとおりの修正を行うでも全く問題はありませんが、動作の確認目的であればTSバージョンを合わせる対応でも問題はないかと思います。

VSCodeの場合は以下の方法でワークスペースのTSバージョンを使用するよう設定することができます。（私はVSCodeのバージョンアップでTSの動作が変わるのを避けるため、基本はワークスペースのTSバージョンを使用するよう設定しています）
https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript
