### ISSUE TITLE
P.29 `vite.config.ts`でのエラー

### ISSUE THREAD

**Issue by phasetr** [SonicGarden/testable-firebase-sample-chat#15]
本のP.29の記述にしたがって`vite.config.ts`を書き換えたら次のエラーが出ました。

```
TS2345: Argument of type '{ plugins: (Plugin_2 | PluginOption[])[]; test: { globals: boolean; environment: string; }; }' is not assignable to parameter of type 'UserConfigExport'.   Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.
```

このリポジトリを見ると`vitest.setup.ts`を参照しているのでそれも追加してみましたが、やはりエラーです。テスト自体は通っています。
完成品（このリポジトリのクローン）ではエラーが出ていないこともあり私の写経ミスやコマンド不実行などを疑っているのですが、どこが悪いのかわかっていません。一応、現状P.34程度まで進んでいる状態のリポジトリも貼っておきます。

- [現状のソースコード](https://github.com/phasetr/testable-firebase-sample-chat)

**Comment by hiroro-work** [comment]
こちら調べてみたところviteとvitestのバージョンによって発生する問題のようです。

https://github.com/vitest-dev/vitest/issues/1537

issueはクローズになっていましたがバージョンの組み合わせによってはクローズ後も発生しているようですので、
一旦はサンプルアプリのライブラリバージョンに合わせていただくのがよいかと思います。

**Comment by phasetr** [comment]
ありがとうございます。バージョンを合わせて問題解決しました。
`yarn.lock`をそのままに`package.json`だけ書き換えていたためずっとはまっていたためご連絡が遅れてしまいました。また続きを読み進めます。
