### ISSUE TITLE
P.50 `<AuthContext.Provider value={{ currentUser }}>`で`型 'User | null | undefined' を型 'User | null' に割り当てることはできません。`のエラー

### ISSUE THREAD

**Issue by phasetr** [SonicGarden/testable-firebase-sample-chat#16]
表題の通り、該当箇所で`currentUser`に対してエラーが出ていて、解消できていません。形式的に
```
type AuthContextValue = {
  currentUser: User | null | undefined;
};
```
とすればエラーは消えますが、P.52時点でのテストが失敗して次のようなエラーが出ます。
> test/contexts/AuthContext.test.tsx [ test/contexts/AuthContext.test.tsx ]
>TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
> ❯ AuthProvider src/contexts/AuthContext.tsx:12:24
>     10| 
>     11| export const AuthProvider = ({children}: { childr…
>     12|   const [currentUser] = useAuthState();
>       |                        ^
>     13|   return <AuthContext.Provider value={{currentUse…
>     14| };

テストでのエラーは二つあり、

> test/rules/firestore/index.test.ts > firestore.rules
>FetchError: request to http://localhost:8080/emulator/v1/projects/fs-sample-open-chat-test:securityRules failed, reason: connect ECONNREFUSED ::1:8080
> ❯ request to http:/localhost:8080/emulator/v1/projects/fs-sample-open-chat-test:securityRules failed, reason: connect ECONNREFUSED ::1:8080
> ❯ ClientRequest.<anonymous> node_modules/node-fetch/lib/index.js:1491:11
>    1489| 
>    1490|               req.on('error', function (err) {
>    1491|                       reject(new FetchError(`request to ${request.ur…
>       |           ^
>    1492|                       finalize();
>    1493|               });
> ❯ ClientRequest.emit node:events:513:28
> ❯ Socket.socketErrorListener node:_http_client:494:9
> ❯ Socket.emit node:events:513:28

も出ているため、rulesの方の問題かとも思ってこちらの本家の`firestore.rules`をコピペで持ってきたのですが、改善しません。問題解決のために何を確認・調査するといいでしょうか？

次のリポジトリは問題が起きている状態です。

- <https://github.com/phasetr/testable-firebase-sample-chat>

**Comment by hiroro-work** [comment]
ご連絡ありがとうございます。

```
type AuthContextValue = {
  currentUser: User | null | undefined;
};
```

こちらに関しては、たしかにこの時点ではundefinedが入ってくる可能性もあるので今のままだとタイプエラーが発生してしまいますね。最終的にはcurrentUserがundefinedの場合はログイン画面を表示するようになるのでundefinedをtypeから削除できるようになりますが、書籍ではその部分を端折って書いてしまっているため、書籍の流れ通りに書いていくと途中でタイプエラーが発生する形になってしまっていました。

**Comment by hiroro-work** [comment]
テストエラーに関してはタイプエラーとは別の原因で発生していると考えられますので調査しないと回答は難しそうですね‥
テストコードをさっと見たところ、以下の行以降がitの外になってしまっているため、そこを修正したらAuthContextのテストに関しては改善するかもしれません。

https://github.com/phasetr/testable-firebase-sample-chat/blob/3-auth/test/contexts/AuthContext.test.tsx#L27

**Comment by hiroro-work** [comment]
firestore.rulesテストのエラーについてですが、テスト実行時にエミュレータは起動していますでしょうか？エラーメッセージを見るとエミュレータに対するリクエストがエラーになっているようなので、エミュレータが正常に起動できていない可能性があるかもしれません。

**Comment by phasetr** [comment]
テストは[頂いたコメント](https://github.com/SonicGarden/testable-firebase-sample-chat/issues/16#issuecomment-1263284682)でのミスを直したら通りました。自分でミスに気づけずお手数お掛けして申し訳ありませんでした。
読み進めて実装を埋めれば`undefined`は消えるとのことなので、一旦このまま進めることにします。ありがとうございました。

**Comment by phasetr** [comment]
メモ：P.59で追加される`if (!currentUser) return <LoginScreen />;`でエラーが解消される。
